### ISSUE TITLE
how can I get relative paths to resolve?

### ISSUE THREAD

**Issue by olets** [ericmorand/gulp-twing#14]
Hi! Coming back to this after a couple busy months…

Following up on #1 and #5: I'm still not clear on how to use relative paths.

The Gulp-y feeling implementation would let users do:

```javascript
const gulp = require('gulp');
const twing = require('gulp-twing');

gulp.task('twig', function() {
    return gulp.src('./src/**/*.twig')
        .pipe(twing())
        .pipe(gulp.dest('./dest'))
});
```

&nbsp;

From #5 I understand that it's something more like

```javascript
const gulp = require('gulp');
const twing = require('gulp-twing');
const Twing = require('twing');
const loader = new Twing.TwingLoaderFilesystem('/');
const env = new Twing.TwingEnvironment(loader);

gulp.task('twig', function() {
    return gulp.src('./src/**/*.twig')
        .pipe(twing(env))
        .pipe(gulp.dest('./dest'));
});
```

That works fine for compiling templates that don't refer to others. But as soon as I try to `include`/`use`/`embed`/etc I'm unable to resolve the path — e.g.

```twig
{# src/index.twig #}
{% include '_include-test.twig' %}
```

```
events.js:183
    throw er; // Unhandled 'error' event
    ^

TwingErrorLoader: Unable to find template "_include-test.twig" (looked into: ) in "src/index.twig" at line 2.
```

&nbsp;

@zomars looking at [zomars/gulp-twing-test/gulpfile.js](https://github.com/zomars/gulp-twing-test/blob/master/gulpfile.js) it looks like I should be able to do something like

```json
"gulp-twing": "github:zomars/gulp-twing#fix-autoreload"
```

```javascript
const gulp = require('gulp');
const twing = require('gulp-twing');
const Twing = require('twing');

gulp.task('twig', function() {
    return gulp.src('./src/**/*.twig')
        .pipe(twing(undefined, {
            templatePaths: ['./src/']
        }))
        .pipe(gulp.dest('./dest'))
});
```

but that gives me

```
events.js:183
    throw er; // Unhandled 'error' event
    ^

TwingErrorLoader: Unable to find template "src/index.twig" (looked into: ./src).
```

At least there the error reports looking in `./src` instead of ``.

(I admit I haven't looked at how `github:zomars/gulp-twing#fix-autoreload` differs from the canonical version.)

&nbsp;

Where am I going wrong? Thanks!

**Comment by ericmorand** [comment]
Twing filesystem loader doesn't support relative path resolving. That comes from TwigPHP filesystem loader that doesn't support it either. I guess gulp-twing can't do miracles there. The official way to deal with relative path resolving is to use namespaces.

Anyway, I'm currently researching how to support relative path resolving without changing the core too much. I want it to stay close to TwigPHP.

**Comment by olets** [comment]
Got it got it, I misunderstood the error. Thanks!

Understanding how to resolve paths could be tricky for any user who doesn't have experience working directly with TwigPHP. I'll open a PR to update the readme.

**Comment by olets** [comment]
Yeah that's very cool 👍

For my usecase (replacing gulp-nunjucks in a website build tool) paths need to resolve relative to an arbitrary directory I have defined:

```
(root)
|
└── src                 <--- defined as twig files path root
    |
    ├── subdirectory-1
    |   |
    |   └── main.twig
    |
    └── subdirectory-2
        |
        └── included.twig
```

```twig
{# subdirectory-1/main.twig #}

{% include 'subdirectory-2/included' %}
```

I think that's different from `TwigLoaderRelativeFilesystem` — I think I still have to add additional paths to the `TwingLoaderFilesystem` as described in #15. Is that right? I know it was long ago and there have been many updates

**Comment by ericmorand** [comment]
Yes in this case TwingLoaderFilesystem is appropriate. Constructed with "src" as root as you did.
