### ISSUE TITLE
[RFC] Add option to change the output file extension

### ISSUE THREAD

**Issue by zomars** [ericmorand/gulp-twing#2]
I have a PR coming soon for this.

**Comment by ericmorand** [comment]
Thanks @zomars.

Isn't this the purpose of gulp-rename? I'm currently sticking with Gulp guidelines:

> Your plugin shouldn't do things that other plugins are responsible for
> It should not concat, gulp-concat does that
> It should not add headers, gulp-header does that
> It should not add footers, gulp-footer does that
> If it's a common but optional use case, document that your plugin is often used with another plugin
> Make use of other plugins within your plugin! This reduces the amount of code you have to write and ensures a stable ecosystem.

So I'm willing to merge your PR but I want to be sure that changing file extension can't be delegated to gulp-rename. Is there something that prevents using gulp-rename with gulp-twing?

**Comment by zomars** [comment]
I've added it as an override-able option with a default value of '.html'. I don't see why not it couldn't be used with gulp-rename.

**Comment by olets** [comment]
Fwiw gulp-twig decided to go with built-in renaming support. The compelling argument was

> gulp-twig should not be assuming I'm writing HTML

I started on the pro-`gulp-rename` side, but @tremby changed my mind: not including built-in support for extension changing effectively penalizes some people who are using Twig in a legitimate way (it forces them to bring in an additional tool). I think of it now as a "what are you compiling to?" option.

https://github.com/zimmen/gulp-twig/issues/19

**Comment by ericmorand** [comment]
The fundamental difference here is that gulp-twing doesn't rename _at all_. gulp-twig was outputing everything to `.html` if I'm not mistaken. gulp-twing will output the file without touching its name - which means that `index.html.twig` will be output as `twing.html.twing`.

It's a deliberate move to have gulp-twing take zero responsibility with the name of the file. Consider the following project:

```
src
\ index.html.twig
\ index.css.twig
```

Having gulp-twing rename the output using the extension passed as an option, would always lead to one of the file being wrongly named in the end. gulp-rename solve that problem very easily.

But enough with the theory. I agree that having to rely on gulp-rename even for the most basic and frequent use cases is a bit of an overkill. And having an option to force the output file extension is not a bad idea at all.

I'll review the PR and will probably add an example with gulp-rename and mixed input file types to highlight that gulp-twing built-in rename function is not a replacement to gulp-rename - I don't want to see some issues later that asks to be able to pass a callback to the rename option. :D

**Comment by zomars** [comment]
I wasn't aware of that discussion but I think my PR provides a solution for both cases. One just would need to create two different tasks for each desired output.
