### ISSUE TITLE
Including Array of Templates

### ISSUE THREAD

**Issue by spacecraft-integration** [ericmorand/gulp-twing#24]
```
{% include [
        template_one.html.twig',
        templates_two.html.twig'
] %}
```

In twig, you can include multiple templates as an array to check for existence before inclusion, the first template that exists will be included.

However here you get the error message:

`
TwingErrorRuntime: An exception has been thrown during the rendering of a template ("Cannot read property 'Symbol(Symbol.iterator)' of object").
`

Would be a nice feature to have this working in the same way if possible?

**Comment by ericmorand** [comment]
@spacecraft-integration, I assume you fixed this issue? This is totally supported by Twing. What was the reason for your issue? Something we should improve maybe?
